package com.gallo.app.util;

public enum NombreCarrera {
    // Centro de Ciencias Agropecuarias
    ING_AGRONOMO,
    ING_EN_ALIMENTOS,
    MEDICO_VETERINARIO_ZOOTECNISTA,

    // Centro de Ciencias Básicas
    ING_BIOQUIMICO,
    ING_EN_COMPUTACION_INTELIGENTE,
    ING_EN_ELECTRONICA,
    ING_EN_SISTEMAS_COMPUTACIONALES,
    ING_INDUSTRIAL_ESTADISTICO,
    LIC_EN_BIOLOGIA,
    LIC_EN_BIOTECNOLOGIA,
    LIC_EN_DESARROLLO_DE_VIDEOJUEGOS_Y_ENTORNOS_VIRTUALES,
    LIC_EN_INFORMATICA_Y_TECNOLOGIAS_COMPUTACIONALES,
    LIC_EN_MATEMATICAS_APLICADAS,
    QUIMICO_FARMACEUTICO_BIOLOGO,

    // Centro de Ciencias de la Ingeniería
    ING_AUTOMOTRIZ,
    ING_BIOMEDICA,
    ING_EN_DISENO_MECANICO,
    ING_EN_ENERGIAS_RENOVABLES,
    ING_EN_MANUFACTURA_Y_AUTOMATIZACION_INDUSTRIAL,
    ING_ROBOTICA,

    // Centro de Ciencias de la Salud
    LIC_EN_CULTURA_FISICA_Y_DEPORTE,
    LIC_EN_ENFERMERIA,
    LIC_EN_NUTRICION,
    LIC_EN_OPTOMETRIA,
    LIC_EN_TERAPIA_FISICA,
    MEDICO_CIRUJANO,
    MEDICO_ESTOMATOLOGO,

    // Centro de Ciencias del Diseño y de la Construcción
    ING_CIVIL,
    LIC_EN_ARQUITECTURA,
    LIC_EN_DISENO_DE_INTERIORES,
    LIC_EN_DISENO_DE_MODA_EN_INDUMENTARIA_Y_TEXTILES,
    LIC_EN_DISENO_GRAFICO,
    LIC_EN_DISENO_INDUSTRIAL,
    LIC_EN_URBANISMO,

    // Centro de Ciencias Económicas y Administrativas
    CONTADOR_PUBLICO,
    LIC_EN_ADMINISTRACION_DE_EMPRESAS,
    LIC_EN_ADMINISTRACION_DE_LA_PRODUCCION_Y_SERVICIOS,
    LIC_EN_ADMINISTRACION_FINANCIERA,
    LIC_EN_COMERCIO_INTERNACIONAL,
    LIC_EN_ECONOMIA,
    LIC_EN_GESTION_TURISTICA,
    LIC_EN_MERCADOTECNIA,
    LIC_EN_RELACIONES_INDUSTRIALES,

    // Centro de Ciencias Empresariales
    LIC_EN_ADMINISTRACION_Y_GESTION_FISCAL_DE_PYMES,
    LIC_EN_AGRONEGOCIOS,
    LIC_EN_COMERCIO_ELECTRONICO,
    LIC_EN_LOGISTICA_EMPRESARIAL,

    // Centro de Ciencias Sociales y Humanidades
    LIC_EN_ASESORIA_PSICOPEDAGOGICA,
    LIC_EN_CIENCIAS_POLITICAS_Y_ADMINISTRACION_PUBLICA,
    LIC_EN_COMUNICACION_CORPORATIVA_ESTRATEGICA,
    LIC_EN_COMUNICACION_E_INFORMACION,
    LIC_EN_DERECHO,
    LIC_EN_DOCENCIA_DE_FRANCES_Y_ESPANOL_COMO_LENGUAS_EXTRANJERAS,
    LIC_EN_DOCENCIA_DEL_IDIOMA_INGLES,
    LIC_EN_FILOSOFIA,
    LIC_EN_HISTORIA,
    LIC_EN_PSICOLOGIA,
    LIC_EN_SOCIOLOGIA,
    LIC_EN_TRABAJO_SOCIAL,

    // Centro de las Artes y la Cultura
    LIC_EN_ACTUACION,
    LIC_EN_ARTES_CINEMATOGRAFICAS_Y_AUDIOVISUALES,
    LIC_EN_ESTUDIOS_DEL_ARTE_Y_GESTION_CULTURAL,
    LIC_EN_LETRAS_HISPANICAS,
    LIC_EN_MUSICA
}
